// Generated by SugarLisp v0.6.5
var sl = require('sugarlisp-core/sl-types');
var match = require('sugarlisp-match/pattern-match');
console.log((
  "\n  <a href=\"http://www.google.com\">" + (
    "\n    <div>" +
    "hello" +
    "\n    </div>") +
  "\n  </a>"));
console.log((
  "\n  <a href=\"http://www.google.com\">" + (
    "\n    <div>" +
    "hello" +
    "\n    </div>") +
  "\n  </a>"));
console.log((
  "\n  <a>" + (
    "\n    <div>" +
    "hello" +
    "\n    </div>") +
  "\n  </a>"));
console.log((
  "\n  <a>" + (
    "\n    <div>" +
    "hello" +
    "\n    </div>") +
  "\n  </a>"));
console.log((
  "\n  <myb href=\"http://www.google.com\">" + (
    "\n    <div>" +
    "hello" +
    "\n    </div>") +
  "\n  </myb>"));
console.log((
  "\n  <myb href=\"http://www.newtek.com\">" + (
    "\n    <div>" +
    "hello" +
    "\n    </div>") +
  "\n  </myb>"));

function myc(attrs, body) {
  return (
    "\n    <a myattr=\"bambam\">" +
    body +
    "\n    </a>");
}
console.log(myc({
  href: "http://www.google.com"
}, (
  "\n  <div>" +
  "hello" +
  "\n  </div>")));
console.log(myc({
  href: "http://www.newtek.com"
}, (
  "\n  <div>" +
  "hello" +
  "\n  </div>")));
var mrflintstone = (
  "\n  <div fname=\"fred\" lname=\"flintstone\">" + [
    "barney",
    "betty",
    "bambam"
  ].forEach(function(elem) {
    return (
      "\n      <a id=\"" + elem + "\">" +
      elem +
      "\n      </a>");
  }) + "\n  " +
  "\n  </div>");
console.log(mrflintstone.toString());

var mrsflintstone = (
"\n  <div fname=\"wilma\" lname=\"flintstone\">" + coll = \"" + [
  "barney",
  "betty",
  "bambam"
] + "\" elem=\"elem\".collection.forEach(function(.attrcoll[
"barney",
"betty",
"bambam"
] elem "elem"
elem) {
  return (
    "\n      <a id=\"" + elem + "\">" +
    elem +
    "\n      </a>");
}) +
"\n  </div>");
console.log(mrsflintstone.toString());