// Generated by SugarLisp v0.5
var mycell = 1;

var mytgt = "?";

console.log(["before anything: ", mytgt].join(''));
mycell = 12;
mytgt = (function(mycell) {
  return ((mycell < 0) ?
    "negative" :
    "positive");
})(mycell)
console.log(["after positive: ", mytgt].join(''));
mycell = -2;
mytgt = (function(mycell) {
  return ((mycell < 0) ?
    "negative" :
    "positive");
})(mycell)
console.log(["after negative: ", mytgt].join(''));