// Generated by SugarLisp v0.5
var a = 0;
var b = 0;

var sum = "?";

console.log(["before anything: ", sum].join(''));
a = 1;
sum = (function(a, b) {
  return (a + b);
})(a, b)
console.log(["after setting a to 1: ", sum].join(''));
b = 2;
sum = (function(a, b) {
  return (a + b);
})(a, b)
console.log(["after setting b to 2: ", sum].join(''));
++a;
sum = (function(a, b) {
  return (a + b);
})(a, b)
console.log(["after pre-incrementing a: ", sum].join(''));
--b;
sum = (function(a, b) {
  return (a + b);
})(a, b)
console.log(["after pre-decrementing b: ", sum].join(''));
a++;
sum = (function(a, b) {
  return (a + b);
})(a, b)
console.log(["after post-incrementing a: ", sum].join(''));
b--;
sum = (function(a, b) {
  return (a + b);
})(a, b)
console.log(["after post-decrementing b: ", sum].join(''));
(a += 2);
sum = (function(a, b) {
  return (a + b);
})(a, b)
console.log(["after a += 2: ", sum].join(''));
(b -= 3);
sum = (function(a, b) {
  return (a + b);
})(a, b)
console.log(["after b -= 3: ", sum].join(''));