// Generated by SugarLisp v0.5

var mrsflintstone = (
    "\n  <div fname=\"wilma\" lname=\"flintstone\">" + Array.prototype.map.call(collection = \"" + [
        "barney",
        "betty",
        "bambam"
      ] + "\" elem=\"character\".collection,function(character) {
      return (
        "\n      <a id=\"" + character + "\">" +
        character +
        "\n      </a>");
    }).join("") +
  "\n  </div>");
console.log(mrsflintstone.toString());