// Generated by SugarLisp v0.5
console.log((
  "\n  <a href=\"http://www.google.com\">" + (
    "\n    <div>" +
    "hello" +
    "\n    </div>") +
  "\n  </a>"));
console.log((
  "\n  <a href=\"http://www.google.com\">" + (
    "\n    <div>" +
    "hello" +
    "\n    </div>") +
  "\n  </a>"));
console.log((
  "\n  <a>" + (
    "\n    <div>" +
    "hello" +
    "\n    </div>") +
  "\n  </a>"));
console.log((
  "\n  <a>" + (
    "\n    <div>" +
    "hello" +
    "\n    </div>") +
  "\n  </a>"));
var mrflintstone = (
  "\n  <div fname=\"fred\" lname=\"flintstone\">" + [
    "barney",
    "betty",
    "bambam"
  ].forEach(function(elem) {
    return (
      "\n      <a id=\"" + elem + "\">" +
      elem +
      "\n      </a>");
  }) + "\n  " +
  "\n  </div>");
console.log(mrflintstone.toString());

var mrsflintstone = (
"\n  <div fname=\"wilma\" lname=\"flintstone\">" + coll = \"" + [
  "barney",
  "betty",
  "bambam"
] + "\" elem=\"elem\".collection.forEach(function(.attrcoll[
"barney",
"betty",
"bambam"
] elem "elem"
elem) {
  return (
    "\n      <a id=\"" + elem + "\">" +
    elem +
    "\n      </a>");
}) +
"\n  </div>");
console.log(mrsflintstone.toString());