// Generated by SugarLisp v0.6.5

function base(title, header, body) {
  return (
    "\n    <html>" + (
      "\n      <head>" + (
        "\n        <title>" +
        title +
        "\n        </title>") + (
        "\n        <meta name=\"pageTitle\" value=\"" + title + "\"/>") +
      "\n      </head>") + (
      "\n      <body>" + (
        "\n        <h1>" +
        header +
        "\n        </h1>") + body + "\n    " +
      "\n      </body>") +
    "\n    </html>");
}

console.log(base("Title", "Header", "Body"));