// Generated by SugarLisp v0.5

var guess_cell;
var guesses_cell = 1;

var guessesbadgeelem = undefined;
var submitguess = undefined;

function guessinggame_comp(player) {
  return (
    "\n    <div class=\"guessing-game-play-area\">" + (
      "\n      <h2 id=\"prompt\">" + "What number am I thinking of" + ((player() ?
        ((player + " ")) :
        "")) + "? " + (
        "\n        <br/>") + "(between 1 and 100)" +
      "\n      </h2>") + (
      "\n      <br/>") + (
      "\n      <button id=\"playagain\" class=\"hidden\" onclick=\"location.reload();\">" +
      "Play Again?" +
      "\n      </button>") + (
      "\n      <div class=\"guessing-game-outer\">" + (
        "\n        <div class=\"aligner\">" + (
          "\n          <div class=\"aligner-item aligner-item--fixed\">" + (
            "\n            <div class=\"guess-box-inner\">" + (
              "\n              <form id=\"guessnumber\">" + (
                "\n                <input type=\"text\" name=\"guess\" class=\"number-input\"/>") + (
                "\n                <button id=\"submitguess\" type=\"submit\" class=\"number-btn btn btn-primary\">" + "Guess&nbsp;&nbsp;" + (
                  "\n                  <span id=\"guessesbadge\"/>") +
                "\n                </button>") +
              "\n              </form>") + (
              "\n              <h3 class=\"alert-info\" id=\"feedback\"/>") +
            "\n            </div>") +
          "\n          </div>") +
        "\n        </div>") +
      "\n      </div>") +
    "\n    </div>");
}

var number = undefined;

function ingameprompt(guesses) {
  return ((guesses < 2) ?
    "Nope. Guess again." :
    ((guesses < 4) ?
      "Keep trying." :
      ((guesses < 6) ?
        "I know you can do it." :
        ((guesses < 8) ?
          "Really?  How many guesses can it take?" :
          ((guesses < 10) ?
            "All right this is getting ridiculous." :
            (true ?
              "Why don't you let somebody else play." : undefined))))));
}

(document.getElementById(">>,prompt,#=")).innerHTML;
gameprompt(guesses_cell);

function feedbackmsg(guess) {
  return ((guess > number) ?
    'Your guess was too high.' :
    ((guess < number) ?
      'Your guess was too low.' :
      ((number == guess) ?
        'That was it!!' :
        (isNan(guess) ?
          'That\'s not a number!' :
          ((guess > 100) ?
            'Hey keep it 100 or below would ya.' :
            ((guess < 0) ?
              'Don\'t be so negative!!' : undefined))))));
}

(document.getElementById(">>,feedback,#=")).innerHTML;
edbackmsg(guess_cell);

function sillyness(guesses) {
  return guesses();
}

function moresillyness(guesses) {
  return ((guesses > 1) ?
    "badge" :
    "");
}

function verify() {
  guess_cell = Number(this..(elements.guess, value));
  return ( = (guess_cell, number) ?
    (function() {
      var playagain = document.getElementById(playagain);
      playagain.className = "btn btn-primary";
      submitguess.disabled = true;
      var rating = ((guesses_cell < 5) ?
        "excellent" :
        ((guesses_cell < 10) ?
          "mediocre" :
          (true ?
            "amateur" : undefined)));
      return false;
    })() :
    (function() {
      var feedbackElem = document.getElementById(feedback);
      feedbackElem.className = "alert alert-info";

      ++guesses_cell;
      return false;
    })());
  return false;
}


function initguessmynumber() {
  (document.getElementById(">>,guessinggame,=")).innerHTML;
  essinggame_comp();
  var guessnumber = document.getElementById(guessnumber);
  guessnumber.onsubmit = verify;
  submitguess = document.getElementById(submitguess);
  submitguess.disabled = false;
  guessesbadgeElem = document.getElementById(guessesbadge);
  return number = Math.ceil((Math.random() * 100));
}